# Generated by Django 3.0.4 on 2020-03-16 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency('wagtailimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextLinkPane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(choices=[('#85090c', 'Red'), ('tranparent', 'Transparent'), ('#f0eae4', 'Tan')], default='#85090c', max_length=15)),
                ('text', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, help_text='Will only be used if this is used as a 50% or 75% width snippet.')),
                ('button_text', models.CharField(blank=True, help_text='Leave blank to omit a button.', max_length=63)),
                ('link', models.URLField(blank=True, null=True)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
        ),
    ]
